// Generated by CoffeeScript 1.4.0
(function() {
  var FormulaVisitor, TreeBuilder,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  FormulaVisitor = (function() {

    function FormulaVisitor() {}

    FormulaVisitor.prototype.visitIntegerLiteral = function(node) {
      return this.visitLiteral(node);
    };

    FormulaVisitor.prototype.visitDecimalLiteral = function(node) {
      return this.visitLiteral(node);
    };

    FormulaVisitor.prototype.visitStringLiteral = function(node) {
      return this.visitLiteral(node);
    };

    FormulaVisitor.prototype.visitParens = function(node) {
      return node.formula.visit(this);
    };

    FormulaVisitor.prototype.visitInfixExpression = function(node, fn) {
      var left, right;
      left = node.left.visit(this);
      right = node.right.visit(this);
      return fn(left, right);
    };

    return FormulaVisitor;

  })();

  TreeBuilder = (function(_super) {

    __extends(TreeBuilder, _super);

    function TreeBuilder() {
      return TreeBuilder.__super__.constructor.apply(this, arguments);
    }

    TreeBuilder.prototype.visitLiteral = function(node) {
      var val;
      val = node.value;
      return {
        name: val,
        value: val
      };
    };

    TreeBuilder.prototype.visitStringLiteral = function(node) {
      var val;
      val = "'" + node.value + "'";
      return {
        name: val,
        value: val
      };
    };

    TreeBuilder.prototype.visitReference = function(node) {
      var val;
      val = node.name;
      return {
        name: val,
        value: val
      };
    };

    TreeBuilder.prototype.visitParens = function(node) {
      var child, val;
      child = node.formula.visit(this);
      val = "( " + child.value + " )";
      return {
        name: '( )',
        children: [child],
        value: val
      };
    };

    TreeBuilder.prototype.visitInfixExpression = function(node) {
      return TreeBuilder.__super__.visitInfixExpression.call(this, node, function(a, b) {
        var op;
        op = node.operator;
        return {
          name: op,
          children: [a, b],
          value: "" + a.value + " " + op + " " + b.value
        };
      });
    };

    TreeBuilder.prototype.visitFunctionCall = function(node) {
      var child, children, param, val;
      children = (function() {
        var _i, _len, _ref, _results;
        _ref = node.parameters;
        _results = [];
        for (_i = 0, _len = _ref.length; _i < _len; _i++) {
          param = _ref[_i];
          _results.push(param.visit(this));
        }
        return _results;
      }).call(this);
      val = "" + node.name + "(";
      if (children.length !== 0) {
        val += " " + (((function() {
          var _i, _len, _results;
          _results = [];
          for (_i = 0, _len = children.length; _i < _len; _i++) {
            child = children[_i];
            _results.push(child.value);
          }
          return _results;
        })()).join(', ')) + " ";
      }
      val += ")";
      return {
        name: "" + node.name + "()",
        children: children,
        value: val
      };
    };

    return TreeBuilder;

  })(FormulaVisitor);

  module.exports = function(formula) {
    return formula.visit(new TreeBuilder());
  };

}).call(this);
